#### Main analysis script ####

# Uncommented `include` statements allow reproducing the main analyses without
# re-running any part multiple time. Commented statements will re-run
# intermediate analysis steps or preparation steps that only need to be run
# once.

# 0. Get the IUCN rasters

# Run this ONLY if you want to download the IUCN rasters for the first time.
# We do not recommended running this script if you already have the rasters used
# in our analyses as the files may change, for instance if there is a new
# assessment for a species.

# include("00_get_rasters.jl")

# 1. Network and range update analysis

# The following files all depend on each other, therefore running the last one
# will also re-run all the previous ones. This is because the intermediate
# objects are too big to be easily exported and version-controlled. Note that
# you can still run script 03, for example, and it will run scripts 01 and 02
# as required.

# include("01-load_rasters.jl")
# include("02-get_networks.jl")
# include("03-analyse_cooccurrence.jl")
# include("04-ranges_diff.jl")
# include("05-degrees.jl")
include("06-scatterplots.jl")

# 2. Summary of range update analyses

# These scripts compute summary statistics, plots, and tables of the previous
# analyses. They can be run independently without re-running the previous
# scripts.

include("07-updated_ranges.jl")
include("08-export_table.jl")

# 3. GBIF analyses

# The following script will create the query to the GBIF download API to
# retrieve the species occurrences. Re-running the 1st part will allow you to
# create a new query for yourself but it will be different from ours as soon as
# new species observations are added.

# In contrast, the 2nd part of this script will always download the exact same
# set of occurrences generated by our own query.

# include("A3_gbif_query.jl")

# Next, the GBIF analysis steps can all be re-ran independently.

include("09-GBIF_data.jl")
include("10-GBIF_comparison.jl")
include("11-GBIF_doublecheck.jl")